### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by roihu-edu**
Added some edits to readme (roihu)

### CODE REVIEW

**Comment by roihu-edu** [comment]
Hi, I made an edit. Can you check it?

**Comment by roihu-edu** [comment]
Sorry, I closed it before you could add it...

**Review by egonzale — APPROVED** [review]
Good, go ahead

**Comment by egonzale** [comment]
Let's merge it.
t. egonzale

**Comment by egonzale** [comment]
maybe not goes through?
t. egonzale

**Pull request merged**
